script: "Oh you don't know what karlson is it's just a game I'm working on currently the %rank most wishlisted game on Steam"
header: |
  ░█░█░█▀█░█▀▄░█░░░█▀▀░█▀█░█▀█
  ░█▀▄░█▀█░█▀▄░█░░░▀▀█░█░█░█░█
  ░▀░▀░▀░▀░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀░▀
